/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abghode' at '1/26/18 3:56 PM' with Gradle 3.1
 *
 * @author abghode, @date 1/26/18 3:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
