/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abghode' at '1/19/18 10:14 AM' with Gradle 3.1
 *
 * @author abghode, @date 1/19/18 10:14 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
